# conda virtual environment for Green book
name: green-book
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - pip
  - conda-lock
  - pandas
  - pre-commit
  - attrs
platforms:
  - osx-64
  - osx-arm64
  - linux-64
