from typing import Dict, Tuple, Sequence

CLASSES: Dict[str, Sequence[Tuple[str, str]]] = {
    "A": [
        ("1", "White Potatoes"),
        ("2", "Coloured Potatoes"),
        ("3", "Onions,"),
        ("4", "Carrots"),
        ("5", "Beetroot"),
        ("6", "Edible Squash/Gourd/Marrow"),
        ("7", "Runner Beans"),
        ("8", "Longest runner bean"),
        ("9", "French Beans"),
        ("10", "Cherry Tomatoes, any variety"),
        ("11", "Tomatoes"),
        ("12", "Courgette"),
        ("13", "Cucumbers"),
        ("14", "Shallots"),
        ("15", "Any other vegetables not included in classes 1 to 14"),
        ("16", "Capsicums including Chili Peppers 17 Container of Mixed Vegetables"),
        ("17", "Container of Mixed Vegetables"),
    ],
    "B": [
        ("18", "Apples,Dessert 19 Apples,Culinary 20 Plums"),
        ("21", "Damsons"),
        ("22", "Pears"),
        ("23", "Soft Fruits"),
        ("24", "Any other fruit not included in classes 18 to 23"),
    ],
    "C": [
        ("25A", "Pompom Dahlias"),
        ("25B", "Cactus & Semi Cactus Dahlias"),
        ("25C", "Decorative Dahlias"),
        ("26", "Roses Floribunda"),
        ("27", "Roses, H/T"),
        ("28", "Single H/T Rose"),
        ("29", "Sweet peas"),
        ("30", "Gladioli"),
        ("31", "Pot plant, Flowering, including Cactus"),
        ("32", "Pot Plant, Foliage, including Ferns"),
        ("33", "Cut Flowers"),
        ("34", "5 cut herbs in a container"),
    ],
    "D": [
        ("35", "Arrangement of Foliage"),
        ("36", "Arrangement of Flowers"),
    ],
    "E": [
        ("37", "Hand baked Bread - No Bread-makers allowed!"),
        ("38", "Bread-maker bread - Only bread-makers allowed!"),
        ("39", "Traditional Plain Shortbread (5 Pieces)"),
        ("40", "Sticky Gingerbread Cake (max 8”)"),
        ("41", "Lemon Drizzle Cake (max 8”)"),
        ("42", "Fruit Cake (max 8”)"),
        ("43", "Classic Coffee Cake (max 8”)"),
        ("44", "5 Plain Scones"),
        ("45", "Peppermint Creams"),
    ],
    "F": [
        ("46", "1 jar of Strawberry Jam"),
        ("47", "1 jar of Marmalade"),
        ("48", "1 jar of Fruit Jelly"),
        ("49", "1 jar of Stone Fruit Jam"),
        ("50", "1 jar of Jam not included in classes 46 to 49"),
        ("51", "1 jar of Chutney, including Piccalilli"),
        ("52", "1 jar of Pickles"),
    ],
    "G": [
        ("53", "Home laid Eggs (any variety)"),
        ("54", "Homemade Beer or Cider"),
        ("55", "Homemade Spirit or Liqueur"),
        ("56", "Homemade Wine"),
        ("57", "Homemade Cordial"),
    ],
    "H": [
        ("58A", "Photographs - anybody"),
        ("58B", "Photographs - animals"),
        ("58C", "Photographs - anywhere"),
        ("58D", "Photographs - arty"),
        ("59", "Cushion in any Medium, (maximum size 18” square)"),
        ("60", "An Original Artwork"),
        ("61", "An Original Line Drawing"),
        ("62", "A Piece of Quilting or Patchwork"),
        ("63", "Handmade greetings card"),
        ("64", "An Upcycled Item"),
        ("65", "A Piece of Poetry"),
    ],
    "I": [
        ("66", "Garden in a Seed Tray"),
        ("67", "A character made from Fruit or Vegetables"),
        ("68", "Most Misshapen Vegetable"),
        ("69", "Scene from history made from Lego (no sets allowed!)"),
    ],
    "J": [
        ("70", "Decorated Fairy Cakes (3 per plate)"),
        ("71", "Garden Flowers in a Jam Jar"),
        ("72", "A piece of Artwork using Recycled Material"),
        ("73", "Garden in a seed tray"),
        ("74", "Any Photograph taken during the current year"),
        ("75", "Scene from history made from Lego (no sets allowed!)"),
    ],
}
